import photo1 from "@/assets/investor-assets/img-01.svg";
import photo2 from "@/assets/investor-assets/img-02.svg";
import photo3 from "@/assets/investor-assets/img-03.svg";
import photo4 from "@/assets/investor-assets/img-01.svg";
import photo5 from "@/assets/investor-assets/img-02.svg";

// Purchase Request Status Enum
export const PURCHASE_REQUEST_STATUS = {
  AWAITING_UPLOAD: 'Awaiting Upload',
  AWAITING_VERIFICATION: 'Awaiting Verification',
  AWAITING_FOR_MINT: 'Awaiting For Mint',
  REJECTED: 'Rejected',
  APPROVED: 'Approved'
};

export const STATUS_FILTERS = [
  { id: "available", label: "Available", count: 18 },
  { id: "funded", label: "Funded", count: 4 },
  { id: "exited", label: "Exited", count: 3 },
];

// Purchase Request Status Filters
export const PURCHASE_REQUEST_STATUS_FILTERS = [
  { id: "all", label: "All" },
  { id: PURCHASE_REQUEST_STATUS.AWAITING_UPLOAD, label: PURCHASE_REQUEST_STATUS.AWAITING_UPLOAD },
  { id: PURCHASE_REQUEST_STATUS.AWAITING_VERIFICATION, label: PURCHASE_REQUEST_STATUS.AWAITING_VERIFICATION },
  { id: PURCHASE_REQUEST_STATUS.AWAITING_FOR_MINT, label: PURCHASE_REQUEST_STATUS.AWAITING_FOR_MINT },
  { id: PURCHASE_REQUEST_STATUS.REJECTED, label: PURCHASE_REQUEST_STATUS.REJECTED },
  { id: PURCHASE_REQUEST_STATUS.APPROVED, label: PURCHASE_REQUEST_STATUS.APPROVED },
];

export const INDUSTRY_OPTIONS = [
  { value: "all", label: "All" },
  { value: "sports-entertainment", label: "Sports & Entertainment" },
  { value: "technology-saas", label: "Technology / SaaS" },
  { value: "healthcare", label: "Healthcare" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "retail", label: "Retail" },
  { value: "hospitality", label: "Hospitality" },
];

export const SORT_OPTIONS = [
  { value: "relevance", label: "Relevance" },
  { value: "investment-low", label: "Amount: Low to High" },
  { value: "investment-high", label: "Amount: High to Low" },
  { value: "tokens-low", label: "Tokens: Low to High" },
  { value: "tokens-high", label: "Tokens: High to Low" },
  { value: "date-new", label: "Date: Newest First" },
  { value: "date-old", label: "Date: Oldest First" },
];

export const ANNUAL_RETURN_FILTERS = [
  { id: "under-5", label: "<5%" },
  { id: "5-10", label: "5-10%" },
  { id: "10-15", label: "10-15%" },
  { id: "over-15", label: ">15%" },
];

export const INVESTMENT_TERM_FILTERS = [
  { id: "short", label: "Short (<2 years)" },
  { id: "medium", label: "Medium (2-5 years)" },
  { id: "long", label: "Long (5+ years)" },
  { id: "ongoing", label: "Ongoing" },
];

export const MINIMUM_INVESTMENT_FILTERS = [
  { id: "500-1k", label: "$500-$1k" },
  { id: "1k-5k", label: "$1k-$5k" },
  { id: "5k-10k", label: "$5k-$10k" },
  { id: "10k-plus", label: "$10k+" },
];

export const OPPORTUNITIES = [
  {
    id: 1,
    image: photo1,
    category: "Pro. Sports & Entertainment",
    location: "London, U.K.",
    title: "European Football Club",
    description:
      "Fractional corporate ownership in the operating company that controls the club's commercial, media, and matchday rights, providing exposure to a top-tier European football brand with deep fan loyalty, regular European competition participation, and diversified revenue streams beyond matchday operations.",
    minInvestment: "$50,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "11.2%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "11.2%",
    investmentTerm: "long",
    minInvestmentValue: 50000,
  },
  {
    id: 2,
    image: photo2,
    category: "Media & Entertainment",
    location: "Los Angeles, CA",
    title: "Tokenized Music Rights Catalog",
    description:
      "Diversified catalog of music rights (master and publishing) across pop, hip-hop, and Latin genres. Tokens represent economic and governance rights over royalty streams generated from streaming, sync licenses, and performance income.",
    minInvestment: "$50,000",
    assetType: "Equity",
    expectedTerm: "Perpetual",
    expectedYield: "7.85%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "7.85%",
    investmentTerm: "ongoing",
    minInvestmentValue: 50000,
  },
  {
    id: 3,
    image: photo3,
    category: "AI & Data Centers",
    location: "Tokyo, Japan",
    title: "Tier-1 AI GPU Data Center",
    description:
      "Next-generation AI and high-performance computing (HPC) data center operator focused on GPU-dense infrastructure for training and inference workloads. The company provides colocation, managed clusters, and 'GPU-as-a-Service' offerings to AI startups, enterprises, and government clients.",
    minInvestment: "$250,000",
    assetType: "Debt",
    expectedTerm: "5 Years",
    expectedYield: "9.25%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "9.25%",
    investmentTerm: "long",
    minInvestmentValue: 250000,
  },
  {
    id: 4,
    image: photo4,
    category: "Real Estate",
    location: "Spain",
    title: "Hotel Marqués de Riscal",
    description:
      "Luxury hotel property in the heart of Spain's wine country, featuring world-class amenities and sustainable architecture. This iconic property offers investors exposure to premium hospitality real estate with strong historical performance.",
    minInvestment: "$75,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "11.2%",
    status: "available",
    industry: "hospitality",
    annualReturn: "11.2%",
    investmentTerm: "long",
    minInvestmentValue: 75000,
  },
  {
    id: 5,
    image: photo1,
    category: "Pro. Sports & Entertainment",
    location: "North America",
    title: "North American Basketball Team",
    description:
      "Ownership stake in a professional basketball franchise with strong brand value, media rights, and arena operations. Provides exposure to sports entertainment industry with diversified revenue streams.",
    minInvestment: "$50,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "11.2%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "11.2%",
    investmentTerm: "long",
    minInvestmentValue: 50000,
  },
  {
    id: 6,
    image: photo5,
    category: "Real Estate",
    location: "United States",
    title: "Mixed-Use Commercial Building",
    description:
      "Prime mixed-use commercial property combining retail, office, and residential spaces in a high-traffic urban location. Offers stable rental income with potential for capital appreciation.",
    minInvestment: "$100,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "11.2%",
    status: "available",
    industry: "hospitality",
    annualReturn: "11.2%",
    investmentTerm: "long",
    minInvestmentValue: 100000,
  },
  {
    id: 7,
    image: photo2,
    category: "Infrastructure",
    location: "Global",
    title: "Renewable Energy Infrastructure Fund",
    description:
      "Diversified portfolio of solar and wind energy projects across multiple regions. Provides stable, long-term returns through power purchase agreements and government incentives.",
    minInvestment: "$150,000",
    assetType: "Equity",
    expectedTerm: "10 Years",
    expectedYield: "8.5%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "8.5%",
    investmentTerm: "long",
    minInvestmentValue: 150000,
  },
  {
    id: 8,
    image: photo3,
    category: "AI & Data Centers",
    location: "Singapore",
    title: "Cloud Computing Infrastructure",
    description:
      "State-of-the-art data center facility providing cloud infrastructure services to enterprise clients. Features advanced cooling systems and renewable energy integration.",
    minInvestment: "$200,000",
    assetType: "Debt",
    expectedTerm: "3 Years",
    expectedYield: "7.2%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "7.2%",
    investmentTerm: "medium",
    minInvestmentValue: 200000,
  },
  {
    id: 9,
    image: photo1,
    category: "Media & Entertainment",
    location: "Los Angeles, CA",
    title: "Film Production Studio",
    description:
      "Established film production facility with multiple sound stages and post-production capabilities. Generates revenue through studio rentals, production services, and content development.",
    minInvestment: "$80,000",
    assetType: "Equity",
    expectedTerm: "7 Years",
    expectedYield: "9.8%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "9.8%",
    investmentTerm: "long",
    minInvestmentValue: 80000,
  },
  {
    id: 10,
    image: photo4,
    category: "Real Estate",
    location: "Dubai, UAE",
    title: "Luxury Residential Tower",
    description:
      "Premium residential development in Dubai's business district, featuring luxury apartments with world-class amenities and stunning views.",
    minInvestment: "$120,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "10.5%",
    status: "available",
    industry: "hospitality",
    annualReturn: "10.5%",
    investmentTerm: "long",
    minInvestmentValue: 120000,
  },
  {
    id: 11,
    image: photo2,
    category: "Pro. Sports & Entertainment",
    location: "Europe",
    title: "European Football League Media Rights",
    description:
      "Investment in media rights for a major European football league, providing exposure to broadcasting revenue streams and digital content distribution.",
    minInvestment: "$60,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "12.5%",
    status: "funded",
    industry: "sports-entertainment",
    annualReturn: "12.5%",
    investmentTerm: "long",
    minInvestmentValue: 60000,
  },
  {
    id: 12,
    image: photo3,
    category: "Infrastructure",
    location: "Australia",
    title: "Port Infrastructure Development",
    description:
      "Modern port facility expansion project supporting increased trade volumes and providing long-term stable returns through port fees and logistics services.",
    minInvestment: "$300,000",
    assetType: "Debt",
    expectedTerm: "8 Years",
    expectedYield: "6.8%",
    status: "funded",
    industry: "technology-saas",
    annualReturn: "6.8%",
    investmentTerm: "long",
    minInvestmentValue: 300000,
  },
  {
    id: 13,
    image: photo5,
    category: "Real Estate",
    location: "New York, USA",
    title: "Manhattan Office Building",
    description:
      "Prime office space in Manhattan's financial district, leased to blue-chip tenants with long-term contracts providing stable rental income.",
    minInvestment: "$500,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "8.2%",
    status: "funded",
    industry: "hospitality",
    annualReturn: "8.2%",
    investmentTerm: "long",
    minInvestmentValue: 500000,
  },
  {
    id: 14,
    image: photo1,
    category: "Media & Entertainment",
    location: "London, UK",
    title: "Music Festival Production Company",
    description:
      "Leading music festival organizer with established brands and multi-year contracts. Generates revenue through ticket sales, sponsorships, and merchandise.",
    minInvestment: "$70,000",
    assetType: "Equity",
    expectedTerm: "4 Years",
    expectedYield: "11.5%",
    status: "funded",
    industry: "sports-entertainment",
    annualReturn: "11.5%",
    investmentTerm: "medium",
    minInvestmentValue: 70000,
  },
  {
    id: 15,
    image: photo2,
    category: "Real Estate",
    location: "Tokyo, Japan",
    title: "Residential Development Project",
    description:
      "Modern residential complex in Tokyo's growing suburbs, targeting young professionals and families with convenient access to public transportation.",
    minInvestment: "$90,000",
    assetType: "Equity",
    expectedTerm: "6 Years",
    expectedYield: "9.5%",
    status: "exited",
    industry: "hospitality",
    annualReturn: "9.5%",
    investmentTerm: "long",
    minInvestmentValue: 90000,
  },
  {
    id: 16,
    image: photo3,
    category: "AI & Data Centers",
    location: "Frankfurt, Germany",
    title: "Enterprise Data Center",
    description:
      "Tier-3 data center facility serving enterprise clients with high-availability requirements. Features redundant power and cooling systems.",
    minInvestment: "$180,000",
    assetType: "Debt",
    expectedTerm: "4 Years",
    expectedYield: "7.8%",
    status: "exited",
    industry: "technology-saas",
    annualReturn: "7.8%",
    investmentTerm: "medium",
    minInvestmentValue: 180000,
  },
  {
    id: 17,
    image: photo4,
    category: "Pro. Sports & Entertainment",
    location: "Miami, USA",
    title: "Sports Training Facility",
    description:
      "State-of-the-art training facility for professional athletes, featuring cutting-edge equipment and sports science laboratories.",
    minInvestment: "$55,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "10.8%",
    status: "exited",
    industry: "sports-entertainment",
    annualReturn: "10.8%",
    investmentTerm: "long",
    minInvestmentValue: 55000,
  },
  {
    id: 18,
    image: photo5,
    category: "Infrastructure",
    location: "Canada",
    title: "Renewable Energy Wind Farm",
    description:
      "Large-scale wind energy project with long-term power purchase agreements. Provides stable returns through renewable energy credits and electricity sales.",
    minInvestment: "$400,000",
    assetType: "Equity",
    expectedTerm: "15 Years",
    expectedYield: "7.5%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "7.5%",
    investmentTerm: "long",
    minInvestmentValue: 400000,
  },
  {
    id: 19,
    image: photo1,
    category: "Real Estate",
    location: "Paris, France",
    title: "Historic Boutique Hotel",
    description:
      "Charming boutique hotel in Paris's historic district, combining classic architecture with modern amenities and personalized service.",
    minInvestment: "$85,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "10.2%",
    status: "available",
    industry: "hospitality",
    annualReturn: "10.2%",
    investmentTerm: "long",
    minInvestmentValue: 85000,
  },
  {
    id: 20,
    image: photo2,
    category: "Media & Entertainment",
    location: "Nashville, USA",
    title: "Country Music Publishing Catalog",
    description:
      "Extensive catalog of country music publishing rights, including hits from established artists and emerging songwriters.",
    minInvestment: "$65,000",
    assetType: "Equity",
    expectedTerm: "Perpetual",
    expectedYield: "8.5%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "8.5%",
    investmentTerm: "ongoing",
    minInvestmentValue: 65000,
  },
  {
    id: 21,
    image: photo3,
    category: "AI & Data Centers",
    location: "Seoul, South Korea",
    title: "Edge Computing Network",
    description:
      "Distributed edge computing infrastructure providing low-latency services for gaming, streaming, and IoT applications across Asia-Pacific.",
    minInvestment: "$220,000",
    assetType: "Debt",
    expectedTerm: "5 Years",
    expectedYield: "8.8%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "8.8%",
    investmentTerm: "long",
    minInvestmentValue: 220000,
  },
  {
    id: 22,
    image: photo4,
    category: "Pro. Sports & Entertainment",
    location: "Barcelona, Spain",
    title: "Sports Media Platform",
    description:
      "Digital media platform focused on sports content, analytics, and fan engagement. Generates revenue through subscriptions and advertising.",
    minInvestment: "$45,000",
    assetType: "Equity",
    expectedTerm: "4 Years",
    expectedYield: "13.2%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "13.2%",
    investmentTerm: "medium",
    minInvestmentValue: 45000,
  },
  {
    id: 23,
    image: photo5,
    category: "Infrastructure",
    location: "Brazil",
    title: "Toll Road Infrastructure",
    description:
      "Modern toll road connecting major economic centers, providing steady cash flow through toll collections and maintenance contracts.",
    minInvestment: "$350,000",
    assetType: "Debt",
    expectedTerm: "12 Years",
    expectedYield: "7.0%",
    status: "available",
    industry: "technology-saas",
    annualReturn: "7.0%",
    investmentTerm: "long",
    minInvestmentValue: 350000,
  },
  {
    id: 24,
    image: photo1,
    category: "Real Estate",
    location: "Sydney, Australia",
    title: "Waterfront Commercial Development",
    description:
      "Mixed-use waterfront development combining retail, dining, and office spaces with stunning harbor views and premium amenities.",
    minInvestment: "$110,000",
    assetType: "Equity",
    expectedTerm: "5 Years",
    expectedYield: "9.8%",
    status: "available",
    industry: "hospitality",
    annualReturn: "9.8%",
    investmentTerm: "long",
    minInvestmentValue: 110000,
  },
  {
    id: 25,
    image: photo2,
    category: "Media & Entertainment",
    location: "Los Angeles, USA",
    title: "Streaming Content Library",
    description:
      "Curated library of premium streaming content including original series, documentaries, and exclusive programming for digital platforms.",
    minInvestment: "$95,000",
    assetType: "Equity",
    expectedTerm: "Perpetual",
    expectedYield: "9.2%",
    status: "available",
    industry: "sports-entertainment",
    annualReturn: "9.2%",
    investmentTerm: "ongoing",
    minInvestmentValue: 95000,
  },
];

