import icon1 from "@/assets/admin-assets/icon2.svg";
import icon2 from "@/assets/admin-assets/icon-1.svg";

export const DUMMY_ADMIN_INVESTMENTS = [
    // Assets Owners (8 records)
    {
      id: 1,
      name: "Miami Sports Club & Entertainment",
      img: icon1,
      email: "Pro. Sports & Entertainment",
      category: "Pro. Sports & Entertainment",
      location: "Miami, FL",
      type: "individual",
      assetsHeld: "$5,000",
      totalTokens: "150",
      totalValue: "$7,500",
      returnValue: "+$7,500 (+30.0%)",
      status: "Asset Holder",
      l_heading: "AST-2025-022",
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "30.0%",
      description:
        "Fractional corporate ownership in the operating company that controls the club's commercial, media, and matchday rights.",
    },
    {
      id: 2,
      name: "Retail Development",
      email: "Real Estate",
      category: "Real Estate",
      location: "New York, NY",
      type: "institutional",
      assetsHeld: "$50,000",
      totalTokens: "1,200",
      totalValue: "$60,000",
      returnValue: "+$3,408 (+28.4%)",
      status: "Asset Holder",
      l_heading: "AST-2025-023",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "7 Years",
      expectedYield: "28.4%",
      description:
        "Fractional ownership in a prime retail development project.",
    },
    {
      id: 3,
      name: "Tech Startup Portfolio Fund",
      email: "Technology / SaaS",
      category: "Technology / SaaS",
      location: "San Francisco, CA",
      type: "individual",
      assetsHeld: "$10,000",
      totalTokens: "300",
      totalValue: "$12,500",
      returnValue: "+$984 (+24.6%)",
      status: "Asset Holder",
      l_heading: "AST-2025-024",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "24.6%",
      description: "Diversified portfolio of early-stage technology startups.",
    },
    {
      id: 4,
      name: "Cayan Tower, Dubai Marina",
      email: "Real Estate",
      category: "Real Estate",
      location: "Dubai, UAE",
      type: "institutional",
      assetsHeld: "$100,000",
      totalTokens: "2,500",
      totalValue: "$125,000",
      returnValue: "+$3,200 (+21.3%)",
      status: "Asset Holder",
      l_heading: "AST-2025-025",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "21.3%",
      description: "Luxury residential property in Dubai Marina.",
    },
    {
      id: 5,
      name: "Green Energy Solar Farm",
      email: "Renewable Energy",
      category: "Energy",
      location: "Phoenix, AZ",
      type: "individual",
      assetsHeld: "$25,000",
      totalTokens: "600",
      totalValue: "$30,000",
      returnValue: "+$4,500 (+18.0%)",
      status: "Asset Holder",
      l_heading: "AST-2025-026",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "10 Years",
      expectedYield: "18.0%",
      description:
        "Solar energy farm with long-term power purchase agreements.",
    },
    {
      id: 6,
      name: "Healthcare Technology Fund",
      email: "Healthcare Tech",
      category: "Healthcare",
      location: "Boston, MA",
      type: "institutional",
      assetsHeld: "$75,000",
      totalTokens: "1,800",
      totalValue: "$90,000",
      returnValue: "+$12,600 (+16.8%)",
      status: "Asset Holder",
      l_heading: "AST-2025-027",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "7 Years",
      expectedYield: "16.8%",
      description: "Portfolio of healthcare technology companies.",
    },
    {
      id: 7,
      name: "Logistics Warehouse Network",
      email: "Industrial Real Estate",
      category: "Logistics",
      location: "Chicago, IL",
      type: "individual",
      assetsHeld: "$40,000",
      totalTokens: "1,000",
      totalValue: "$50,000",
      returnValue: "+$7,000 (+16.4%)",
      status: "Asset Holder",
      l_heading: "AST-2025-028",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "8 Years",
      expectedYield: "16.4%",
      description: "Network of logistics warehouses in strategic locations.",
    },
    {
      id: 8,
      name: "AI Technology Venture Fund",
      email: "Artificial Intelligence",
      category: "Technology",
      location: "Austin, TX",
      type: "institutional",
      assetsHeld: "$60,000",
      totalTokens: "1,500",
      totalValue: "$75,000",
      returnValue: "+$10,500 (+16.3%)",
      status: "Asset Holder",
      l_heading: "AST-2025-029",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "6 Years",
      expectedYield: "16.3%",
      description: "Venture fund focused on AI technology startups.",
    },

    // Verified (2 records)
    {
      id: 9,
      name: "Biotech Research Facility",
      email: "Biotechnology",
      category: "Healthcare",
      location: "San Diego, CA",
      type: "individual",
      assetsHeld: "$35,000",
      totalTokens: "850",
      totalValue: "$42,500",
      returnValue: "+$6,375 (+17.7%)",
      status: "Verified",
      l_heading: "AST-2025-030",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "9 Years",
      expectedYield: "17.7%",
      description:
        "State-of-the-art biotech research and development facility.",
    },
    {
      id: 10,
      name: "Data Center Portfolio",
      email: "Technology Infrastructure",
      category: "Technology",
      location: "Ashburn, VA",
      type: "institutional",
      assetsHeld: "$90,000",
      totalTokens: "2,200",
      totalValue: "$110,000",
      returnValue: "+$15,400 (+16.3%)",
      status: "Verified",
      l_heading: "AST-2025-031",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "10 Years",
      expectedYield: "16.3%",
      description:
        "Portfolio of tier-3 data centers with major cloud providers.",
    },

    // KYC (3 records)
    {
      id: 11,
      name: "Luxury Hotel Resort",
      email: "Hospitality",
      category: "Real Estate",
      location: "Miami Beach, FL",
      type: "individual",
      assetsHeld: "$55,000",
      totalTokens: "1,350",
      totalValue: "$68,750",
      returnValue: "+$9,625 (+16.3%)",
      status: "KYC Submitted ",
      l_heading: "AST-2025-032",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "12 Years",
      expectedYield: "16.3%",
      description: "Luxury beachfront hotel and resort property.",
    },
    {
      id: 12,
      name: "E-commerce Logistics",
      email: "E-commerce",
      category: "Logistics",
      location: "Memphis, TN",
      type: "institutional",
      assetsHeld: "$45,000",
      totalTokens: "1,100",
      totalValue: "$56,250",
      returnValue: "+$7,875 (+16.3%)",
      status: "KYC Submitted",
      l_heading: "AST-2025-033",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "7 Years",
      expectedYield: "16.3%",
      description: "Specialized logistics network for e-commerce fulfillment.",
    },
    {
      id: 13,
      name: "Pharma Manufacturing",
      email: "Pharmaceuticals",
      category: "Healthcare",
      location: "New Jersey, NJ",
      type: "individual",
      assetsHeld: "$65,000",
      totalTokens: "1,600",
      totalValue: "$81,250",
      returnValue: "+$11,375 (+16.3%)",
      status: "KYC Submitted",
      l_heading: "AST-2025-034",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "15 Years",
      expectedYield: "16.3%",
      description: "Pharmaceutical manufacturing facility with FDA approvals.",
    },

    // Basic (2 records)
    {
      id: 14,
      name: "Student Housing Portfolio",
      email: "Student Housing",
      category: "Real Estate",
      location: "Columbus, OH",
      type: "institutional",
      assetsHeld: "$30,000",
      totalTokens: "750",
      totalValue: "$37,500",
      returnValue: "+$5,250 (+16.3%)",
      status: "Basic",
      l_heading: "AST-2025-035",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "10 Years",
      expectedYield: "16.3%",
      description: "Portfolio of student housing properties near universities.",
    },
    {
      id: 15,
      name: "Mobile Gaming Studio",
      email: "Gaming Technology",
      category: "Technology",
      location: "Los Angeles, CA",
      type: "individual",
      assetsHeld: "$20,000",
      totalTokens: "500",
      totalValue: "$25,000",
      returnValue: "+$3,500 (+16.3%)",
      status: "Basic",
      l_heading: "AST-2025-036",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "16.3%",
      description: "Mobile gaming development studio with multiple titles.",
    },

    // Suspended (2 records)
    {
      id: 16,
      name: "Casino Resort Development",
      email: "Hospitality & Gaming",
      category: "Entertainment",
      location: "Las Vegas, NV",
      type: "institutional",
      assetsHeld: "$85,000",
      totalTokens: "2,100",
      totalValue: "$106,250",
      returnValue: "+$14,875 (+16.3%)",
      status: "Suspended",
      l_heading: "AST-2025-037",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "8 Years",
      expectedYield: "16.3%",
      description: "Integrated casino and resort development on the Strip.",
    },
    {
      id: 17,
      name: "Cryptocurrency Mining",
      email: "Blockchain Technology",
      category: "Technology",
      location: "Cheyenne, WY",
      type: "individual",
      assetsHeld: "$50,000",
      totalTokens: "1,250",
      totalValue: "$62,500",
      returnValue: "+$8,750 (+16.3%)",
      status: "Suspended",
      l_heading: "AST-2025-038",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "16.3%",
      description: "Cryptocurrency mining facility with renewable energy.",
    },

    // Disabled (2 records)
    {
      id: 18,
      name: "Agricultural Technology",
      email: "AgriTech",
      category: "Agriculture",
      location: "Des Moines, IA",
      type: "institutional",
      assetsHeld: "$40,000",
      totalTokens: "1,000",
      totalValue: "$50,000",
      returnValue: "+$7,000 (+16.3%)",
      status: "Disabled",
      l_heading: "AST-2025-039",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "10 Years",
      expectedYield: "16.3%",
      description: "Advanced agricultural technology and vertical farming.",
    },
    {
      id: 19,
      name: "Maritime Shipping",
      email: "Shipping & Logistics",
      category: "Transportation",
      location: "Houston, TX",
      type: "individual",
      assetsHeld: "$70,000",
      totalTokens: "1,750",
      totalValue: "$87,500",
      returnValue: "+$12,250 (+16.3%)",
      status: "Disabled",
      l_heading: "AST-2025-040",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "12 Years",
      expectedYield: "16.3%",
      description: "Fleet of maritime shipping containers and vessels.",
    },

    // Denied/Revoked (2 records)
    {
      id: 20,
      name: "Nuclear Energy Research",
      email: "Energy Research",
      category: "Energy",
      location: "Oak Ridge, TN",
      type: "institutional",
      assetsHeld: "$95,000",
      totalTokens: "2,375",
      totalValue: "$118,750",
      returnValue: "+$16,625 (+16.3%)",
      status: "Denied",
      l_heading: "AST-2025-041",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "20 Years",
      expectedYield: "16.3%",
      description: "Advanced nuclear energy research facility.",
    },
    {
      id: 21,
      name: "Space Technology Fund",
      email: "Aerospace",
      category: "Technology",
      location: "Cape Canaveral, FL",
      type: "individual",
      assetsHeld: "$80,000",
      totalTokens: "2,000",
      totalValue: "$100,000",
      returnValue: "+$14,000 (+16.3%)",
      status: "Denied",
      l_heading: "AST-2025-042",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "15 Years",
      expectedYield: "16.3%",
      description: "Venture fund focused on space technology and exploration.",
    },

    // Invited (2 records)
    {
      id: 22,
      name: "EV Charging Network",
      email: "Electric Vehicles",
      category: "Transportation",
      location: "Portland, OR",
      type: "institutional",
      assetsHeld: "$25,000",
      totalTokens: "625",
      totalValue: "$31,250",
      returnValue: "+$4,375 (+16.3%)",
      status: "Invited",
      l_heading: "AST-2025-043",
      img: icon2,
      assetType: "Equity",
      expectedTerm: "8 Years",
      expectedYield: "16.3%",
      description: "Nationwide electric vehicle charging station network.",
    },
    {
      id: 23,
      name: "Virtual Reality Gaming",
      email: "VR Technology",
      category: "Technology",
      location: "Seattle, WA",
      type: "individual",
      assetsHeld: "$15,000",
      totalTokens: "375",
      totalValue: "$18,750",
      returnValue: "+$2,625 (+16.3%)",
      status: "Invited",
      l_heading: "AST-2025-044",
      img: icon1,
      assetType: "Equity",
      expectedTerm: "6 Years",
      expectedYield: "16.3%",
      description: "Virtual reality gaming platform and development studio.",
    },
  ];