import img1 from "@/assets/investor-assets/img-01.svg";
import img2 from "@/assets/investor-assets/img-02.svg";
import img3 from "@/assets/investor-assets/img-03.svg";

export const DUMMY_INVESTMENTS = [
    {
      id: 1,
      name: "Miami Sports Club & Entertainment",
      img: img3,
      email: "Pro. Sports & Entertainment",
      category: "Pro. Sports & Entertainment",
      location: "Miami, FL",
      type: "individual",
      assetsHeld: "$5,000",
      totalTokens: "150",
      totalValue: "$7,500",
      returnValue: "+$7,500 (+30.0%)",
      status: "Active",
      l_heading: "AST-2025-022",
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "30.0%",
      description: "Fractional corporate ownership in the operating company that controls the club's commercial, media, and matchday rights, providing exposure to a top-tier sports brand with deep fan loyalty and diversified revenue streams.",
    },
    {
      id: 2,
      name: "Retail Development",
      email: "Real Estate",
      category: "Real Estate",
      location: "New York, NY",
      type: "institutional",
      assetsHeld: "$50,000",
      totalTokens: "1,200",
      totalValue: "$60,000",
      returnValue: "+$3,408 (+28.4%)",
      status: "Funded",
      l_heading: "AST-2025-022",
      img: img2,
      assetType: "Equity",
      expectedTerm: "7 Years",
      expectedYield: "28.4%",
      description: "Fractional ownership in a prime retail development project located in a high-traffic urban area, offering stable rental income and potential for capital appreciation.",
    },
    {
      id: 3,
      name: "Tech Startup Portfolio Fund",
      email: "Technology / SaaS",
      category: "Technology / SaaS",
      location: "San Francisco, CA",
      type: "individual",
      assetsHeld: "$10,000",
      totalTokens: "300",
      totalValue: "$12,500",
      returnValue: "+$984 (+24.6%)",
      status: "Active",
      l_heading: "AST-2025-022",
      img: img1,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "24.6%",
      description: "Diversified portfolio of early-stage technology startups focused on SaaS solutions, providing exposure to high-growth potential companies in the technology sector.",
    },
    {
      id: 4,
      name: "2 Bed in Cayan Tower, Dubai Marina",
      email: "Real Estate",
      category: "Real Estate",
      location: "Dubai, UAE",
      type: "institutional",
      assetsHeld: "$100,000",
      totalTokens: "2,500",
      totalValue: "$125,000",
      returnValue: "+$3,200 (+21.3%)",
      status: "Exited",
      l_heading: "AST-2025-022",
      img: img3,
      assetType: "Equity",
      expectedTerm: "5 Years",
      expectedYield: "21.3%",
      description: "Luxury residential property in Dubai Marina featuring premium amenities and stunning waterfront views, offering strong rental yields and capital appreciation potential.",
    },
    {
      id: 1,
      name: "Miami Sports Club & Entertainment",
      img: img1,
      email: "AI & Technology",
      type: "individual",
      assetsHeld: "$5,000",
      totalTokens: "150",
      totalValue: "$7,500",
      returnValue: "+$700 (+20.0%)",
      status: "Active",
      l_heading: "AST-2025-022",
    },
    {
      id: 2,
      name: "Retail Development",
      email: "Real Estate",
      type: "institutional",
      assetsHeld: "$50,000",
      totalTokens: "1,200",
      totalValue: "$60,000",
      returnValue: "+8%",
      status: "Funded",
      l_heading: "AST-2025-022",
      img: img2,
    },
    {
      id: 3,
      name: "Tech Startup Portfolio Fund",
      email: "Business Equity",
      type: "individual",
      assetsHeld: "$10,000",
      totalTokens: "300",
      totalValue: "$12,500",
      returnValue: "+$1,800 (+18.0%)",
      status: "Active",
      l_heading: "AST-2025-022",
      img: img3,
    },
    {
      id: 4,
      name: "2 Bed in Cayan Tower, Dubai Marina",
      email: "Real Estate",
      type: "institutional",
      assetsHeld: "$100,000",
      totalTokens: "2,500",
      totalValue: "$125,000",
      returnValue: "+$1,800 (+13.3%)",
      status: "Exited",
      l_heading: "AST-2025-022",
      img: img3,
    },
    {
      id: 1,
      name: "Miami Sports Club & Entertainment",
      img: img1,
      email: "AI & Technology",
      type: "individual",
      assetsHeld: "$5,000",
      totalTokens: "150",
      totalValue: "$7,500",
      returnValue: "+12%",
      status: "Active",
      l_heading: "AST-2025-022",
    },
    {
      id: 2,
      name: "Retail Development",
      email: "Real Estate",
      type: "institutional",
      assetsHeld: "$50,000",
      totalTokens: "1,200",
      totalValue: "$60,000",
      returnValue: "+$5,000 (+10.0%)",
      status: "Funded",
      l_heading: "AST-2025-022",
      img: img2,
    },
    {
      id: 3,
      name: "Tech Startup Portfolio Fund",
      email: "Business Equity",
      type: "individual",
      assetsHeld: "$10,000",
      totalTokens: "300",
      totalValue: "$12,500",
      returnValue: "+15%",
      status: "Active",
      l_heading: "AST-2025-022",
      img: img3,
    },
    {
      id: 4,
      name: "2 Bed in Cayan Tower, Dubai Marina",
      email: "Real Estate",
      type: "institutional",
      assetsHeld: "$100,000",
      totalTokens: "2,500",
      totalValue: "$125,000",
      returnValue: "+$5,000 (+10.0%)",
      status: "Exited",
      l_heading: "AST-2025-022",
      img: img3,
    },
    {
      id: 3,
      name: "Tech Startup Portfolio Fund",
      email: "Business Equity",
      type: "individual",
      assetsHeld: "$10,000",
      totalTokens: "300",
      totalValue: "$12,500",
      returnValue: "+15%",
      status: "Active",
      l_heading: "AST-2025-022",
      img: img3,
    },
    {
      id: 4,
      name: "2 Bed in Cayan Tower, Dubai Marina",
      email: "Real Estate",
      type: "institutional",
      assetsHeld: "$100,000",
      totalTokens: "2,500",
      totalValue: "$125,000",
      returnValue: "+$5,000 (+10.0%)",
      status: "Exited",
      l_heading: "AST-2025-022",
      img: img3,
    },
  ];