import {
  FaLeaf,
  FaWheatAwn,
  FaStethoscope,
  FaDna,
  FaSolarPanel,
  FaBuilding,
  FaChartLine,
  FaGear,
  FaDroplet,
  FaIndustry,
  FaCartShopping,
  FaTruck,
  FaUser,
  FaCloud,
  FaMicrochip,
} from "react-icons/fa6";

export const ASSETS_DATA = [
  {
    id: 1,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 11, 2025",
    icon: FaWheatAwn,
  },

  {
    id: 11,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Denied",
    statusType: "denied",
    date: "Nov 8, 2025",
    icon: FaStethoscope,
  },
  
  {
    id: 5,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-047",
    requestId: "REQ-2025-010",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Approved",
    statusType: "approved",
    date: "Nov 7, 2025",
    icon: FaLeaf,
  },
  {
    id: 16,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-047",
    requestId: "REQ-2025-010",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Minted",
    statusType: "minted",
    date: "Nov 7, 2025",
    icon: FaLeaf,
    address: "0xc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e",
  },
  {
    id: 2,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 11, 2025",
    icon: FaWheatAwn,
  },
  {
    id: 7,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Approved",
    statusType: "approved",
    date: "Nov 11, 2025",
    icon: FaWheatAwn,
  },
  {
    id: 8,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Approved",
    statusType: "approved",
    date: "Nov 8, 2025",
    icon: FaDna,
  },
  {
    id: 9,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-027",
    requestId: "REQ-2025-025",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    initialMint: "4,500,000",
    totalSupply: "4,500,000",
    capitalTarget: "$40,000,000",
    status: "Denied",
    statusType: "denied",
    date: "Oct 28, 2025",
    icon: FaStethoscope,
  },
  {
    id: 3,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-047",
    requestId: "REQ-2025-010",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 7, 2025",
    icon: FaLeaf,
  },
  {
    id: 10,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Denied",
    statusType: "denied",
    date: "Nov 8, 2025",
    icon: FaStethoscope,
  },

  {
    id: 4,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 8, 2025",
    icon: FaDna,
  },
  {
    id: 12,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Denied",
    statusType: "denied",
    date: "Nov 8, 2025",
    icon: FaStethoscope,
  },
  {
    id: 13,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Minted",
    statusType: "minted",
    date: "Nov 8, 2025",
    icon: FaDna,
    address: "0x8f7a9b3c4d5e6f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d1c",
  },
  {
    id: 14,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-035",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Minted",
    statusType: "minted",
    date: "Nov 8, 2025",
    icon: FaDna,
    address: "0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
  },
  {
    id: 15,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Minted",
    statusType: "minted",
    date: "Nov 11, 2025",
    icon: FaWheatAwn,
    address: "0xb2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d",
  },
  {
    id: 21,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-047",
    requestId: "REQ-2025-010",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Minted",
    statusType: "minted",
    date: "Nov 7, 2025",
    icon: FaLeaf,
    address: "0xc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e",
  },
  {
    id: 17,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-045",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Published",
    statusType: "published",
    date: "Nov 8, 2025",
    icon: FaDna,
  },
  {
    id: 18,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-045",
    requestId: "REQ-2025-015",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Published",
    statusType: "published",
    date: "Nov 8, 2025",
    icon: FaDna,
  },
  {
    id: 19,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Published",
    statusType: "published",
    date: "Nov 11, 2025",
    icon: FaWheatAwn,
  },
  {
    id: 20,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-047",
    requestId: "REQ-2025-010",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Published",
    statusType: "published",
    date: "Nov 7, 2025",
    icon: FaLeaf,
  },
];

export const TOKENIZATION_REQUESTS_DATA = [
  // Pending Review Items (First Image - 8 items with Review button)

  {
    id: 17,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-012",
    requestId: "REQ-2025-007",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Published",
    statusType: "published",
    date: "Nov 13, 2025",
    icon: FaWheatAwn,
  },
  {
    id: 1,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-012",
    requestId: "REQ-2025-007",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaWheatAwn,
  },
  {
    id: 2,
    name: "Sunrise Solar Fund",
    category: "Solar Energy",
    assetId: "AST-2025-042",
    requestId: "REQ-2025-007",
    issuer: "Solar Ventures LLC",
    issuerEmail: "info@solarventures.com",
    initialMint: "8,000,000",
    totalSupply: "8,000,000",
    capitalTarget: "$62,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaSolarPanel,
  },
  {
    id: 3,
    name: "Downtown Plaza LLC",
    category: "Commercial Real Estate",
    assetId: "AST-2025-003",
    requestId: "REQ-2025-007",
    issuer: "Plaza Management Inc.",
    issuerEmail: "management@plaza.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaBuilding,
  },
  {
    id: 4,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-104",
    requestId: "REQ-2025-007",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    initialMint: "4,500,000",
    totalSupply: "4,500,000",
    capitalTarget: "$40,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaStethoscope,
  },
  {
    id: 5,
    name: "Urban Development",
    category: "Real Estate Development",
    assetId: "AST-2025-199",
    requestId: "REQ-2025-007",
    issuer: "Urban Properties LLC",
    issuerEmail: "properties@urban.com",
    initialMint: "7,500,000",
    totalSupply: "7,500,000",
    capitalTarget: "$35,500,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaBuilding,
  },
  {
    id: 6,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-143",
    requestId: "REQ-2025-007",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaLeaf,
  },
  {
    id: 7,
    name: "Techsource",
    category: "Enterprise Analytics Software",
    assetId: "AST-2025-011",
    requestId: "REQ-2025-007",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    initialMint: "5,000,000",
    totalSupply: "5,000,000",
    capitalTarget: "$50,500,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaChartLine,
  },
  {
    id: 8,
    name: "TechStart AI Platform",
    category: "Technology SaaS",
    assetId: "AST-2025-033",
    requestId: "REQ-2025-007",
    issuer: "FinTech Solutions Inc.",
    issuerEmail: "contact@fintechsolutions.com",
    initialMint: "500,000",
    totalSupply: "500,000",
    capitalTarget: "$50,000,000",
    status: "Pending Review",
    statusType: "pending",
    date: "Nov 13, 2025",
    icon: FaGear,
  },

  // Ready to Mint Items (Second Image - 5 items with Mint button)
  {
    id: 9,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-007",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    initialMint: "10,000,000",
    totalSupply: "10,000,000",
    capitalTarget: "$50,000,000",
    status: "Ready to Mint",
    statusType: "minted",
    date: "Nov 13, 2025",
    icon: FaDna,
  },
  {
    id: 10,
    name: "Clean Water Initiative",
    category: "Environmental Services",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-007",
    issuer: "Water Solutions Inc.",
    issuerEmail: "contact@watersolutions.com",
    initialMint: "20,000,000",
    totalSupply: "20,000,000",
    capitalTarget: "$190,250,000",
    status: "Ready to Mint",
    statusType: "minted",
    date: "Nov 13, 2025",
    icon: FaDroplet,
  },
  {
    id: 11,
    name: "Manufacturing Excellence",
    category: "Industrial Manufacturing",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-007",
    issuer: "Precision Industries",
    issuerEmail: "info@precision.com",
    initialMint: "4,000,000",
    totalSupply: "4,000,000",
    capitalTarget: "$38,000,000",
    status: "Ready to Mint",
    statusType: "minted",
    date: "Nov 13, 2025",
    icon: FaIndustry,
  },
  {
    id: 12,
    name: "Retail Technology Platform",
    category: "Retail Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-007",
    issuer: "RetailTech Corp",
    issuerEmail: "info@retailtech.com",
    initialMint: "4,500,000",
    totalSupply: "4,500,000",
    capitalTarget: "$40,000,000",
    status: "Ready to Mint",
    statusType: "minted",
    date: "Nov 13, 2025",
    icon: FaCartShopping,
  },
  {
    id: 16,
    name: "Smart Logistics Network",
    category: "Supply Chain Tech",
    assetId: "AST-2025-022",
    requestId: "REQ-2025-007",
    issuer: "Logistics Innovations",
    issuerEmail: "hello@logistics.com",
    initialMint: "9,000,000",
    totalSupply: "9,000,000",
    capitalTarget: "$180,000,000",
    status: "Ready to Mint",
    statusType: "minted",
    date: "Nov 13, 2025",
    icon: FaTruck,
  },

];

export const ISSUANCE_QUEUE_DATA = [
  // Pending Issuance (12 items)
  {
    id: 1,
    name: "IBCL AI",
    category: "AI & Technology",
    assetId: "AST-2025-042",
    requestId: "TIR-2025-109",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    purchaser: "Morgan Stanley Wealth",
    purchaserContact: "James Chen",
    purchaserEmail: "james.chen@ms.com",
    purchaserType: "company",
    tokens: "2,500",
    amount: "$250,000",
    date: "Nov 14, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaMicrochip,
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop",
  },
  {
    id: 2,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-029",
    requestId: "TIR-2025-032",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    purchaser: "Emily Rodriguez",
    purchaserContact: "Emily Rodriguez",
    purchaserEmail: "emily.r@gmail.com",
    purchaserType: "individual",
    tokens: "1,000",
    amount: "$250,000",
    date: "Nov 13, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaLeaf,
    imageUrl: null,
  },
  {
    id: 3,
    name: "Cloud Aqua",
    category: "Sustainability",
    assetId: "AST-2025-091",
    requestId: "TIR-2025-108",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    purchaser: "Michael Thompson",
    purchaserContact: "Michael Thompson",
    purchaserEmail: "m.thompson@yahoo.com",
    purchaserType: "individual",
    tokens: "500",
    amount: "$60,000",
    date: "Nov 11, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaCloud,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=100&h=100&fit=crop",
  },
  {
    id: 4,
    name: "TechStart AI Platform",
    category: "Enterprise Analytics Software",
    assetId: "AST-2025-067",
    requestId: "TIR-2025-021",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    purchaser: "Goldman Sachs Private Wealth",
    purchaserContact: "Lisa Wang",
    purchaserEmail: "lwang@gs.com",
    purchaserType: "company",
    tokens: "5,000",
    amount: "$500,000",
    date: "Nov 11, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaChartLine,
    imageUrl: null,
  },
  // Tokens Issued (10 items)
  {
    id: 5,
    name: "Green Energy Solutions",
    category: "Renewable Energy",
    assetId: "AST-2025-034",
    requestId: "TIR-2025-008",
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    purchaser: "Emily Rodriguez",
    purchaserContact: "Emily Rodriguez",
    purchaserEmail: "emily.r@gmail.com",
    purchaserType: "individual",
    tokens: "1,000",
    amount: "$250,000",
    date: "Nov 15, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0x4Tg6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6Hy2",
    icon: FaLeaf,
    imageUrl: null,
  },
  {
    id: 6,
    name: "Cloud Aqua",
    category: "Sustainability",
    assetId: "AST-2025-032",
    requestId: "TIR-2025-008",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    purchaser: "Michael Thompson",
    purchaserContact: "Michael Thompson",
    purchaserEmail: "m.thompson@yahoo.com",
    purchaserType: "individual",
    tokens: "500",
    amount: "$60,000",
    date: "Nov 15, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0x4Fr5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f45Tg",
    icon: FaCloud,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=100&h=100&fit=crop",
  },
  {
    id: 7,
    name: "TechStart AI Platform",
    category: "Enterprise Analytics Software",
    assetId: "AST-2025-016",
    requestId: "TIR-2025-008",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    purchaser: "Goldman Sachs Private Wealth",
    purchaserContact: "Lisa Wang",
    purchaserEmail: "lwang@gs.com",
    purchaserType: "company",
    tokens: "5,000",
    amount: "$500,000",
    date: "Nov 14, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0x8fyZa7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d2d1c",
    icon: FaChartLine,
    imageUrl: null,
  },
  {
    id: 8,
    name: "Urban Development Co",
    category: "Real Estate Development",
    assetId: "AST-2025-021",
    requestId: "TIR-2025-008",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    purchaser: "UBS Wealth Management",
    purchaserContact: "David Kumar",
    purchaserEmail: "dkumar@ubs.com",
    purchaserType: "company",
    tokens: "3,000",
    amount: "$75,000",
    date: "Nov 11, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0x4Tg6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6Hy2",
    icon: FaBuilding,
    imageUrl: null,
  },
  // Additional Pending Issuance items (8 more to reach 12)
  {
    id: 9,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-055",
    requestId: "TIR-2025-045",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    purchaser: "JPMorgan Chase",
    purchaserContact: "Sarah Johnson",
    purchaserEmail: "sarah.j@jpmorgan.com",
    purchaserType: "company",
    tokens: "4,000",
    amount: "$400,000",
    date: "Nov 10, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaDna,
    imageUrl: null,
  },
  {
    id: 10,
    name: "HealthTech Diagnostics",
    category: "Medical Devices",
    assetId: "AST-2025-078",
    requestId: "TIR-2025-067",
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    purchaser: "Robert Martinez",
    purchaserContact: "Robert Martinez",
    purchaserEmail: "r.martinez@outlook.com",
    purchaserType: "individual",
    tokens: "750",
    amount: "$90,000",
    date: "Nov 9, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaStethoscope,
    imageUrl: null,
  },
  {
    id: 11,
    name: "AgriTech Solutions",
    category: "Agriculture Tech",
    assetId: "AST-2025-033",
    requestId: "TIR-2025-056",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    purchaser: "Credit Suisse",
    purchaserContact: "Thomas Anderson",
    purchaserEmail: "t.anderson@credit-suisse.com",
    purchaserType: "company",
    tokens: "6,000",
    amount: "$600,000",
    date: "Nov 8, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaWheatAwn,
    imageUrl: null,
  },
  {
    id: 12,
    name: "Sunrise Solar Fund",
    category: "Solar Energy",
    assetId: "AST-2025-044",
    requestId: "TIR-2025-078",
    issuer: "Solar Ventures LLC",
    issuerEmail: "info@solarventures.com",
    purchaser: "Jennifer Lee",
    purchaserContact: "Jennifer Lee",
    purchaserEmail: "j.lee@hotmail.com",
    purchaserType: "individual",
    tokens: "1,500",
    amount: "$150,000",
    date: "Nov 7, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaSolarPanel,
    imageUrl: null,
  },
  {
    id: 13,
    name: "Downtown Plaza LLC",
    category: "Commercial Real Estate",
    assetId: "AST-2025-061",
    requestId: "TIR-2025-089",
    issuer: "Plaza Management Inc.",
    issuerEmail: "management@plaza.com",
    purchaser: "Barclays Wealth",
    purchaserContact: "Amanda White",
    purchaserEmail: "a.white@barclays.com",
    purchaserType: "company",
    tokens: "2,200",
    amount: "$220,000",
    date: "Nov 6, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaBuilding,
    imageUrl: null,
  },
  {
    id: 14,
    name: "Manufacturing Excellence",
    category: "Industrial Manufacturing",
    assetId: "AST-2025-072",
    requestId: "TIR-2025-092",
    issuer: "Precision Industries",
    issuerEmail: "info@precision.com",
    purchaser: "Christopher Brown",
    purchaserContact: "Christopher Brown",
    purchaserEmail: "c.brown@gmail.com",
    purchaserType: "individual",
    tokens: "800",
    amount: "$80,000",
    date: "Nov 5, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaIndustry,
    imageUrl: null,
  },
  {
    id: 15,
    name: "Retail Technology Platform",
    category: "Retail Tech",
    assetId: "AST-2025-085",
    requestId: "TIR-2025-101",
    issuer: "RetailTech Corp",
    issuerEmail: "info@retailtech.com",
    purchaser: "Deutsche Bank",
    purchaserContact: "Maria Garcia",
    purchaserEmail: "m.garcia@db.com",
    purchaserType: "company",
    tokens: "3,500",
    amount: "$350,000",
    date: "Nov 4, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaCartShopping,
    imageUrl: null,
  },
  {
    id: 16,
    name: "Smart Logistics Network",
    category: "Supply Chain Tech",
    assetId: "AST-2025-096",
    requestId: "TIR-2025-112",
    issuer: "Logistics Innovations",
    issuerEmail: "hello@logistics.com",
    purchaser: "Daniel Kim",
    purchaserContact: "Daniel Kim",
    purchaserEmail: "d.kim@yahoo.com",
    purchaserType: "individual",
    tokens: "1,200",
    amount: "$120,000",
    date: "Nov 3, 2025",
    status: "Pending Issuance",
    statusType: "pending",
    icon: FaTruck,
    imageUrl: null,
  },
  // Additional Tokens Issued items (6 more to reach 10)
  {
    id: 17,
    name: "IBCL AI",
    category: "AI & Technology",
    assetId: "AST-2025-041",
    requestId: "TIR-2025-007",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    purchaser: "Morgan Stanley Wealth",
    purchaserContact: "James Chen",
    purchaserEmail: "james.chen@ms.com",
    purchaserType: "company",
    tokens: "2,500",
    amount: "$250,000",
    date: "Nov 13, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
    icon: FaMicrochip,
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop",
  },
  {
    id: 18,
    name: "Urban Development Co",
    category: "Real Estate Development",
    assetId: "AST-2025-019",
    requestId: "TIR-2025-006",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    purchaser: "UBS Wealth Management",
    purchaserContact: "David Kumar",
    purchaserEmail: "dkumar@ubs.com",
    purchaserType: "company",
    tokens: "3,000",
    amount: "$75,000",
    date: "Nov 12, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xb2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d",
    icon: FaBuilding,
    imageUrl: null,
  },
  {
    id: 19,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-053",
    requestId: "TIR-2025-005",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    purchaser: "JPMorgan Chase",
    purchaserContact: "Sarah Johnson",
    purchaserEmail: "sarah.j@jpmorgan.com",
    purchaserType: "company",
    tokens: "4,000",
    amount: "$400,000",
    date: "Nov 10, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e",
    icon: FaDna,
    imageUrl: null,
  },
  {
    id: 20,
    name: "Sunrise Solar Fund",
    category: "Solar Energy",
    assetId: "AST-2025-043",
    requestId: "TIR-2025-004",
    issuer: "Solar Ventures LLC",
    issuerEmail: "info@solarventures.com",
    purchaser: "Jennifer Lee",
    purchaserContact: "Jennifer Lee",
    purchaserEmail: "j.lee@hotmail.com",
    purchaserType: "individual",
    tokens: "1,500",
    amount: "$150,000",
    date: "Nov 9, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f",
    icon: FaSolarPanel,
    imageUrl: null,
  },
  {
    id: 21,
    name: "Downtown Plaza LLC",
    category: "Commercial Real Estate",
    assetId: "AST-2025-060",
    requestId: "TIR-2025-003",
    issuer: "Plaza Management Inc.",
    issuerEmail: "management@plaza.com",
    purchaser: "Barclays Wealth",
    purchaserContact: "Amanda White",
    purchaserEmail: "a.white@barclays.com",
    purchaserType: "company",
    tokens: "2,200",
    amount: "$220,000",
    date: "Nov 8, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xe5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6",
    icon: FaBuilding,
    imageUrl: null,
  },
  {
    id: 22,
    name: "Manufacturing Excellence",
    category: "Industrial Manufacturing",
    assetId: "AST-2025-071",
    requestId: "TIR-2025-002",
    issuer: "Precision Industries",
    issuerEmail: "info@precision.com",
    purchaser: "Christopher Brown",
    purchaserContact: "Christopher Brown",
    purchaserEmail: "c.brown@gmail.com",
    purchaserType: "individual",
    tokens: "800",
    amount: "$80,000",
    date: "Nov 7, 2025",
    status: "Tokens Issued",
    statusType: "issued",
    address: "0xf6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7",
    icon: FaIndustry,
    imageUrl: null,
  },
  // Additional Pending Approval items (6 more to reach 10)
  {
    id: 23,
    name: "IBCL AI",
    category: "AI & Technology",
    assetId: "AST-2025-041",
    requestId: "TIR-2025-007",
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    purchaser: "Morgan Stanley Wealth",
    purchaserContact: "James Chen",
    purchaserEmail: "james.chen@ms.com",
    purchaserType: "company",
    tokens: "2,500",
    amount: "$250,000",
    date: "Nov 13, 2025",
    status: "Pending Approval",
    statusType: "pending-approval",
    address: "0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
    icon: FaMicrochip,
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop",
  },
  {
    id: 24,
    name: "Urban Development Co",
    category: "Real Estate Development",
    assetId: "AST-2025-019",
    requestId: "TIR-2025-006",
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    purchaser: "UBS Wealth Management",
    purchaserContact: "David Kumar",
    purchaserEmail: "dkumar@ubs.com",
    purchaserType: "company",
    tokens: "3,000",
    amount: "$75,000",
    date: "Nov 12, 2025",
    status: "Pending Approval",
    statusType: "pending-approval",
    address: "0xb2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d",
    // icon: FaBuilding,
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop",
  },
  {
    id: 25,
    name: "BioTech Research Corp",
    category: "Biotechnology",
    assetId: "AST-2025-053",
    requestId: "TIR-2025-005",
    issuer: "BioTech Holdings",
    issuerEmail: "research@biotech.com",
    purchaser: "JPMorgan Chase",
    purchaserContact: "Sarah Johnson",
    purchaserEmail: "sarah.j@jpmorgan.com",
    purchaserType: "company",
    tokens: "4,000",
    amount: "$400,000",
    date: "Nov 10, 2025",
    status: "Pending Approval",
    statusType: "pending-approval",
    address: "0xc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e",
    // icon: FaDna,
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop",
  },
];

export const ISSUERS_DATA = [
  {
    id: 1,
    issuer: "AgriTech Innovations",
    issuerEmail: "hello@agritech.com",
    assets: 8,
    totalTokensIssued: "320,000",
    lastActive: "Oct 30, 2025",
    capitalTarget: "320,000",
    submitted: "Oct 30, 2025",
    paymentStatus: "Inactive",
    status: "Inactive",
  },
  {
    id: 2,
    issuer: "GreenTech Holdings",
    issuerEmail: "info@greentech.com",
    assets: 4,
    totalTokensIssued: "120,000",
    lastActive: "Nov 9, 2025",
    capitalTarget: "120,000",
    submitted: "Nov 9, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
  {
    id: 3,
    issuer: "FinTech Solutions Inc.",
    issuerEmail: "contact@fintechsolutions.com",
    assets: 5,
    totalTokensIssued: "180,000",
    lastActive: "Oct 28, 2025",
    capitalTarget: "180,000",
    submitted: "Oct 28, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
  {
    id: 4,
    issuer: "MedTech Innovations",
    issuerEmail: "hello@medtech.com",
    assets: 15,
    totalTokensIssued: "680,000",
    lastActive: "Nov 8, 2025",
    capitalTarget: "680,000",
    submitted: "Nov 8, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
  {
    id: 5,
    issuer: "Solar Ventures LLC",
    issuerEmail: "info@solarventures.com",
    assets: 6,
    totalTokensIssued: "245,000",
    lastActive: "Nov 7, 2025",
    capitalTarget: "245,000",
    submitted: "Nov 7, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
  {
    id: 6,
    issuer: "TechCorp Inc.",
    issuerEmail: "contact@techcorp.com",
    assets: 9,
    totalTokensIssued: "380,000",
    lastActive: "Nov 5, 2025",
    capitalTarget: "380,000",
    submitted: "Nov 5, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
  {
    id: 7,
    issuer: "Urban Properties LLC",
    issuerEmail: "properties@urban.com",
    assets: 12,
    totalTokensIssued: "450,000",
    lastActive: "Nov 10, 2025",
    capitalTarget: "450,000",
    submitted: "Nov 10, 2025",
    paymentStatus: "Active",
    status: "Active",
  },
];

export const SHAREHOLDERS_DATA = [
  {
    id: 1,
    name: "TechCorp Inc.",
    email: "contact@techcorp.com",
    type: "institutional",
    assetsHeld: 12,
    totalTokens: "145,000",
    totalValue: "$8,800,000",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    type: "individual",
    assetsHeld: 3,
    totalTokens: "12,500",
    totalValue: "$625,000",
  },
  {
    id: 3,
    name: "GreenEnergy Solutions",
    email: "info@greenenergy.com",
    type: "institutional",
    assetsHeld: 8,
    totalTokens: "98,000",
    totalValue: "$4,900,000",
  },
  {
    id: 4,
    name: "Michael Chen",
    email: "michael.chen@email.com",
    type: "individual",
    assetsHeld: 5,
    totalTokens: "28,000",
    totalValue: "$1,400,000",
  },
  {
    id: 5,
    name: "Manufacturing Corp",
    email: "contact@manufacturing.com",
    type: "institutional",
    assetsHeld: 6,
    totalTokens: "72,000",
    totalValue: "$3,600,000",
  },
  {
    id: 6,
    name: "Diana White",
    email: "diana.white@email.com",
    type: "individual",
    assetsHeld: 2,
    totalTokens: "8,500",
    totalValue: "$425,000",
  },
  {
    id: 7,
    name: "Robert Martinez",
    email: "robert.m@email.com",
    type: "individual",
    assetsHeld: 4,
    totalTokens: "15,000",
    totalValue: "$750,000",
  },
  {
    id: 8,
    name: "Skyline Investments",
    email: "info@skyline.com",
    type: "institutional",
    assetsHeld: 9,
    totalTokens: "125,000",
    totalValue: "$6,300,000",
  },
  {
    id: 9,
    name: "James Wilson",
    email: "james.wilson@email.com",
    type: "individual",
    assetsHeld: 1,
    totalTokens: "5,000",
    totalValue: "$250,000",
  },
  {
    id: 10,
    name: "Global Finance Group",
    email: "contact@globalfinance.com",
    type: "institutional",
    assetsHeld: 10,
    totalTokens: "110,000",
    totalValue: "$5,500,000",
  },
  {
    id: 11,
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    type: "individual",
    assetsHeld: 3,
    totalTokens: "18,000",
    totalValue: "$900,000",
  },
  {
    id: 12,
    name: "Industrial Holdings",
    email: "info@industrial.com",
    type: "institutional",
    assetsHeld: 7,
    totalTokens: "85,000",
    totalValue: "$4,250,000",
  },
  {
    id: 13,
    name: "David Kim",
    email: "david.kim@email.com",
    type: "individual",
    assetsHeld: 4,
    totalTokens: "22,000",
    totalValue: "$1,100,000",
  },
  {
    id: 14,
    name: "Capital Ventures",
    email: "contact@capitalventures.com",
    type: "institutional",
    assetsHeld: 11,
    totalTokens: "135,000",
    totalValue: "$6,750,000",
  },
  {
    id: 15,
    name: "Lisa Anderson",
    email: "lisa.a@email.com",
    type: "individual",
    assetsHeld: 2,
    totalTokens: "10,000",
    totalValue: "$500,000",
  },
  {
    id: 16,
    name: "Strategic Partners LLC",
    email: "info@strategic.com",
    type: "institutional",
    assetsHeld: 8,
    totalTokens: "95,000",
    totalValue: "$4,750,000",
  },
  {
    id: 17,
    name: "Thomas Brown",
    email: "thomas.brown@email.com",
    type: "individual",
    assetsHeld: 3,
    totalTokens: "16,000",
    totalValue: "$800,000",
  },
];

// Holdings data
export const HOLDINGS_DATA = [
  {
    id: 1,
    assetName: "Green Energy Solutions",
    assetCategory: "Renewable Energy",
    assetId: "AST-2025-022",
    issuer: "GreenTech Holdings",
    issuerEmail: "chris.bronson@greentech.com",
    tokensHeld: "5,000",
    ownershipPercent: "15.0%",
    currentValue: "$150,000",
    acquired: "Oct 25, 2025",
  },
  {
    id: 2,
    assetName: "TechStart AI Platform",
    assetCategory: "Enterprise Analytics Software",
    assetId: "AST-2025-021",
    issuer: "TechCorp Inc.",
    issuerEmail: "john.smith@techcorp.com",
    tokensHeld: "1,000",
    ownershipPercent: "10.0%",
    currentValue: "$100,000",
    acquired: "Oct 10, 2025",
  },
  {
    id: 3,
    assetName: "Downtown Plaza",
    assetCategory: "Commercial Real Estate",
    assetId: "AST-2025-012",
    issuer: "Atlas Enterprises",
    issuerEmail: "j.rosco@brownreality.com",
    tokensHeld: "750",
    ownershipPercent: "7.5%",
    currentValue: "$37,500",
    acquired: "Sep 30, 2025",
  },
];

// Transactions data
export const TRANSACTIONS_DATA = [
  {
    id: 1,
    dateTime: "October 25, 2025",
    time: "11:30 AM",
    assetName: "Green Energy Solutions",
    assetCategory: "Renewable Energy",
    assetId: "AST-2025-022",
    fromName: "GreenTech Holdings",
    fromContact: "John Smith",
    fromEmail: "john.smith@greentech.com",
    tokens: "1,000",
    tokenValue: "$100,000",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
    // Transaction receipt data
    requestId: "REQ-2025-138",
    assetType: "Renewable Energy",
    to: "Michael Chen",
    tokensTransferred: "500",
    amountPaid: "$375,000",
    paymentMethod: "Wire Transfer",
    paymentReference: "WT-2025-8348",
    fullTxHash: "0x742d35Cc6634C0532925a3b8",
  },
  {
    id: 2,
    dateTime: "October 20, 2025",
    time: "11:30 AM",
    assetName: "Atlas Data AI",
    assetCategory: "AI & Technology",
    assetId: "AST-2025-145",
    fromName: "GreenTech Holdings",
    fromContact: "John Smith",
    fromEmail: "john.smith@greentech.com",
    tokens: "500",
    tokenValue: "$50,000",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
  },
  {
    id: 3,
    dateTime: "October 10, 2025",
    time: "11:30 AM",
    assetName: "TechStart AI Platform",
    assetCategory: "Enterprise Analytics Software",
    assetId: "AST-2025-196",
    fromName: "GreenTech Holdings",
    fromContact: "John Smith",
    fromEmail: "john.smith@greentech.com",
    tokens: "500",
    tokenValue: "$50,000",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
  },
  {
    id: 4,
    dateTime: "September 25, 2025",
    time: "11:30 AM",
    assetName: "Exclusive Football Club",
    assetCategory: "Sports & Entertainment",
    assetId: "AST-2025-045",
    fromName: "TechCorp Inc.",
    fromContact: "Joey Buttafuko",
    fromEmail: "j.buttafuko@techcorp.com",
    tokens: "300",
    tokenValue: "$30,000",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
  },
  {
    id: 5,
    dateTime: "September 15, 2025",
    time: "11:30 AM",
    assetName: "Downtown Plaza",
    assetCategory: "Commercial Real Estate",
    assetId: "AST-2025-109",
    fromName: "TechCorp Inc.",
    fromContact: "Joey Buttafuko",
    fromEmail: "j.buttafuko@techcorp.com",
    tokens: "750",
    tokenValue: "$37,500",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
  },
  {
    id: 6,
    dateTime: "August 10, 2025",
    time: "11:30 AM",
    assetName: "Solaris AI",
    assetCategory: "Sustainability",
    assetId: "AST-2025-145",
    fromName: "TechCorp Inc.",
    fromContact: "Joey Buttafuko",
    fromEmail: "j.buttafuko@techcorp.com",
    tokens: "200",
    tokenValue: "$20,000",
    transactionHash: "TIR-2025-138",
    txHash: "0x8fyZ..2d1c",
    txHashFull: "0x8fyZ1234567890abcdef1234567890abcdef2d1c",
  },
];

// Purchase Requests data (based on ISSUANCE_QUEUE_DATA)
export const PURCHASE_REQUESTS_DATA = ISSUANCE_QUEUE_DATA.map((item) => ({
  ...item,
  requestId: item.requestId,
  totalTokensIssued: item.tokens,
  totalValue: item.amount,
  latestUpdate: item.date,
  status: item.status === "Pending Issuance" ? "Pending Issuance" : "Issued",
  statusType: item.statusType === "pending" ? "pending" : "issued",
}));

// Activity Log data
export const ACTIVITY_LOG_DATA = [
  {
    id: 1,
    dateTime: "Nov 19, 2025",
    time: "10:30 AM",
    category: "Asset",
    categoryIcon: FaBuilding,
    activity: "Submitted for Review",
    relatedEntity: {
      name: "Downtown Plaza",
      category: "Commercial Real Estate",
      assetId: "AST-2025-012",
      icon: FaBuilding,
    },
    details: {
      requestId: "REQ-2025-143",
      tokens: "10,000 Tokens",
      target: "$50,000,000 Target",
    },
  },
  {
    id: 2,
    dateTime: "Nov 18, 2025",
    time: "3:15 PM",
    category: "Asset",
    categoryIcon: FaBuilding,
    activity: "Approved by Registrar",
    relatedEntity: {
      name: "Urban Living Complex",
      category: "Residential Real Estate",
      assetId: "AST-2025-018",
      icon: FaBuilding,
    },
    details: {
      requestId: "REQ-2025-152",
      tokens: "10,000 tokens",
    },
  },
  {
    id: 3,
    dateTime: "Nov 17, 2025",
    time: "11:20 AM",
    category: "Token Issuance",
    categoryIcon: FaChartLine,
    activity: "Request Received",
    relatedEntity: {
      name: "Riverside Apartments",
      category: "Residential Real Estate",
      assetId: "AST-2025-018",
      icon: FaBuilding,
    },
    details: {
      requestId: "TIR-2025-089",
      tokens: "1,000 Tokens",
      purchaser: "Michael Chen",
      amount: "$75,000",
    },
  },
  {
    id: 4,
    dateTime: "Nov 16, 2025",
    time: "2:45 PM",
    category: "Asset",
    categoryIcon: FaBuilding,
    activity: "Published to Marketplace",
    relatedEntity: {
      name: "TechStart AI Platform",
      category: "Technology",
      assetId: "AST-2025-021",
      icon: FaChartLine,
    },
    details: {
      requestId: "REQ-2025-148",
      tokens: "5,000 Tokens",
    },
  },
  {
    id: 5,
    dateTime: "Nov 15, 2025",
    time: "9:10 AM",
    category: "Token Issuance",
    categoryIcon: FaChartLine,
    activity: "Tokens Issued",
    relatedEntity: {
      name: "Green Energy Solutions",
      category: "Renewable Energy",
      assetId: "AST-2025-034",
      icon: FaLeaf,
    },
    details: {
      requestId: "TIR-2025-008",
      tokens: "1,000 Tokens",
      purchaser: "Emily Rodriguez",
      amount: "$250,000",
    },
  },
  {
    id: 6,
    dateTime: "Nov 14, 2025",
    time: "4:20 PM",
    category: "Asset",
    categoryIcon: FaBuilding,
    activity: "Denied by Registrar",
    relatedEntity: {
      name: "HealthTech Diagnostics",
      category: "Medical Devices",
      assetId: "AST-2025-104",
      icon: FaStethoscope,
    },
    details: {
      requestId: "REQ-2025-013",
      reason: "Incomplete documentation",
    },
  },
  {
    id: 7,
    dateTime: "Nov 13, 2025",
    time: "1:30 PM",
    category: "Token Issuance",
    categoryIcon: FaChartLine,
    activity: "Request Received",
    relatedEntity: {
      name: "IBCL AI",
      category: "AI & Technology",
      assetId: "AST-2025-042",
      icon: FaMicrochip,
    },
    details: {
      requestId: "TIR-2025-109",
      tokens: "2,500 Tokens",
      purchaser: "Morgan Stanley Wealth",
      amount: "$250,000",
    },
  },
  {
    id: 8,
    dateTime: "Nov 12, 2025",
    time: "11:00 AM",
    category: "Asset",
    categoryIcon: FaBuilding,
    activity: "Minted Successfully",
    relatedEntity: {
      name: "Urban Development Co",
      category: "Real Estate Development",
      assetId: "AST-2025-199",
      icon: FaBuilding,
    },
    details: {
      requestId: "REQ-2025-014",
      tokens: "7,500,000 Tokens",
    },
  },
];