const urls = {
  AUTH: {
    SIGNIN: "/auth/signin",
    VALIDATE_EMAIL: "/auth/validate-email",
    SIGNUP_OTP_REQUEST: "/auth/signup/otp-request",
    SIGNUP_OTP_VERIFY: "/auth/signup/otp-verify",
    SIGNUP: "/auth/signup",
    FORGOT_PASSWORD: "/auth/forgot-password",
    FORGOT_PASSWORD_VERIFY_OTP: "/auth/forgot-password/verify-otp",
    FORGOT_PASSWORD_CONFIRM: "/auth/forgot-password/confirm",
    PROFILE: "/user",
    UPDATE_PROFILE: "/user",
    UPDATE_PASSWORD: "/user/password",
    UPDATE_PROFILE_PIC: "/user/profile-pic",
    UPLOAD_FILE: "/user/upload",
  },
  INVITATIONS: {
    CREATE: "/invitation",
    GET: "/invitation",
    CANCEL: (id) => `/invitation/${id}/cancel`,
    RESEND: (id) => `/invitation/${id}/resent`,
  },
  ASSETS: {
    GET_TOKENIZED_ASSETS: "/tokenized-assets",
    GET_ASSET_DETAILS: (id) => `/tokenized-assets/${id}/details`,
    GET_ASSET_TYPES: "/asset-types",
    CREATE_BASIC_INFORMATION: "/tokenized-assets/basic-information",
    UPDATE_BUSINESS_DETAILS: (id) => `/tokenized-assets/${id}/business-details`,
    UPDATE_FINANCIAL_DETAILS: (id) => `/tokenized-assets/${id}/financial-details`,
    UPDATE_TOKENIZATION_DETAILS: (id) => `/tokenized-assets/${id}/tokenization-details`,
    UPDATE_INITIAL_OWNER: (id) => `/tokenized-assets/${id}/initial-owners`,
    DELETE_INITIAL_OWNER: (assetId, ownerId) => `/tokenized-assets/${assetId}/initial-owners/${ownerId}/remove`,
    UPDATE_ASSET_FILES: (assetId, slug, type) => `/tokenized-assets/${assetId}/files/${slug}/type/${type}`,
    DELETE_ASSET_FILE: (assetId, fileId) => `/tokenized-assets/${assetId}/files/${fileId}/delete`,
    PUBLISH_ASSET: (assetId) => `/tokenized-assets/${assetId}/approval-request`,
    APPROVE_ASSET: (assetTokenizationId) => `/tokenized-assets/${assetTokenizationId}/approval`,
    DENY_ASSET: (assetTokenizationId) => `/tokenized-assets/${assetTokenizationId}/denied`,
    MINT_ASSET: (assetTokenizationId) => `/tokenized-assets/${assetTokenizationId}/minting`,
    UPDATE_MARKETPLACE: (assetTokenizationId) => `/tokenized-assets/${assetTokenizationId}/marketplace`,
    UPDATE_FEATURED_IMAGE: (assetTokenizationId, type) => `/tokenized-assets/${assetTokenizationId}/image/${type}/logo-featured`,
    CREATE_UPDATE_SPONSOR: (assetTokenizationId) => `/tokenized-assets/${assetTokenizationId}/sponser`,
    DELETE_SPONSOR: (assetTokenizationId, sponsorId) => `/tokenized-assets/${assetTokenizationId}/delete/${sponsorId}/sponser`,
    CREATE_PURCHASE_REQUEST: (assetTokenizationId) => `/purchase-request/${assetTokenizationId}/order`,
    GET_PURCHASE_REQUEST_ORDER: (purchaseRequestId) => `/purchase-request/${purchaseRequestId}/order`,
    GET_PURCHASE_REQUEST_DETAIL: (purchaseRequestId) => `/purchase-request/${purchaseRequestId}/detail`,
    GET_PURCHASE_REQUESTS: "/purchase-request",
    APPROVE_ORDER: (purchaseRequestId) => `/purchase-request/${purchaseRequestId}/approve-order`,
    REJECT_ORDER: (purchaseRequestId) => `/purchase-request/${purchaseRequestId}/reject-order`,
    MINT_PURCHASE_REQUEST: (purchaseRequestId) => `/purchase-request/${purchaseRequestId}/minting`,
    ASSIGN_REGISTRAR: (assetTokenizationId, userId) => `/tokenized-assets/${assetTokenizationId}/assign/${userId}/registrar`,
  },
  ROLES: {
    GET: "/roles",
  },
  KYC: {
    SUBMIT: "/user/kyc",
    UPLOAD_ACCREDITATION_FILE: "/user/kyc/accrediation-file",
    DELETE_ACCREDITATION_FILE: (accreditationFileId) =>
      `/user/kyc/${accreditationFileId}/accrediation-file`,
    GET_KYC_USERS: (status) => `/user/kyc/${status}/list`,
    CHANGE_STATUS: "/user/kyc/change-status",
  },
  INVESTORS: {
    GET_STATS: "/user/investors-stats",
  },
};
export default urls;
